[homepage]
  layout = "page"
  showRecent = true
  showRecentItems = 12
  cardView = true

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = false
  showTableOfContents = true
  showRelatedContent = true
  showBreadcrumbs = true

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true

[privacy]
  disablePrivacySettings = true
